### ISSUE TITLE
Create/update content for new pages

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/edgi-website#10]
- [x] About (~remove contact info?~ )
  - [x] Initial restructure
  - [x] standardize image size, bio lengths
  - [x] add key member bios
  - [x] add funding details
  - [x] move airtable to partners
  - ~add organizational structure?~
- [x] About/Steering Committee
  - ~should governance details go here?~
  - [x] remove non-SC members
- [x] About/Members
  - [x] move non-SC members
  - [x] confirm member/partner count! (updated to May 15)
  - [x] add member bios! (done til May 15)

**Update**:
- [x] Publications
  - [x] convert reports to post or custom content type 
  - [x] confirm whether weekly digests should also be posted? (and moved off dropbox) (YES! moved to #13)
- ~Calendar~ (moved to #20) 
  - ~experiment with using events plugin and import from csv (something like [the event calendar](https://theeventscalendar.com/product/wordpress-events-calendar/)~
- [x] Web Archiving/Primers ( Abby and @mayaad to update content)
  - [x] Archiving page created
  - ~reshape the Primers Database content?~ moved to #19
- [x] Press
  - [x] Clean up formatting
  - [x] Look into moving op-eds into "syndication"...?
- [x] Website Monitoring (additional TODOs in #13)
  - [x] Clean up language, confirm name (e.g. tracking team vs. monitoring)
  - [x] Confirm wth "Bill Tracker" is and why it is under here... (moved to C&G
  - [x] Confirm wth "Agency Info" is (not under Monitoring)

**Create**:
- [x] About/EDGI members
  - [x] move details from contact page?
- [x] Our Work/Interviewing
- [x] Our Work/Archiving
- [x] Our Work/C&G
- ~Our Work/FOIA status (who provides site content?!?)~ (seeking clarification #21)
- ~Get Involved/Contact your legislator  (who provides site content?!? what is this function?!)~ (seeking clarification #21)

**Comment by dcwalk** [comment]
Who we need to contact for web content:
- Interviewing Project Chris/Phil/Sarah: @lourdesvera 
- Building Capacity and Governance @dcwalk
- Archiving section (@dcwalk)

**Comment by lourdesvera** [comment]
Phil wrote content for the Interview project page. I made a page [here](https://envirodatagov.org/the-interview-project/). It's not linked to any parent page yet.

**Comment by dcwalk** [comment]
Draft Archiving page: https://envirodatagov.org/archiving/
Draft C&G page: https://envirodatagov.org/capacity-and-governance/

**Comment by dcwalk** [comment]
I am closing this as we've broken out remaining TODOs into their own issues, most require further investigation before action
