### ISSUE TITLE
Rethink Sidebar structure/content

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/edgi-website#17]
We've had some feedback about how we want to handle the sidebar (and which pages have it!)

from @murphyofglad :
> 14. Instead of tags on side bar, upcoming events listing might be more useful to people interms of widget, if the event calendar has that capacity. (sidebar:  top going down: textbox with two sentence EDGI description, recent posts, event calendar. Get involved button.)~ (@dcwalk: tags removed, reticketing sidebar convo)

**Comment by lourdesvera** [comment]
I made the "donate now" button White #FFFFFF
