### ISSUE TITLE
Geographic map of EDGI member orgs and individuals

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/edgi-website#23]
Slack: https://edgi.slack.com/archives/C3EF5T7T6/p1496439256823037

> rando comment not tied to above convo: has there been any talk around *embedded a map of edgi member individuals and orgs*?
>
> there was a mention of "here's a thing for NYC people" and while looking at the reaction emojis, I realized I had only partial sense of where we all lived :slightly_smiling_face:
>
> my initial imagining was just a map, perhaps generated from an airtable member list, showing city-level pin for each person and org, colored differently (perhaps names for orgs, none for people)
>
> also, does the website have a code repo for creating issues for things like this?

**Comment by dcwalk** [comment]
How is this separate from #24 @patcon ?

**Comment by patcon** [comment]
Sorry, this is literally for a geo map, not a "network map" :)

**Comment by lourdesvera** [comment]
oops, I thought the other request was for a geo map and marked it done. Welp, this is done. 
![image](https://user-images.githubusercontent.com/23300449/37068096-028ad602-217b-11e8-819d-c529231f4d14.png)
