### ISSUE TITLE
Resize images

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/edgi-website#25]
Aiii, @patcon points out in https://github.com/edgi-govdata-archiving/100days/issues/2:

> just my 2c, but I like it as-is. The recent webdev trend of cover images strikes me as introducing lots of page bloat that's a bit hostile to visitors with slow internet speeds ¯\_(ツ)_/¯
> Example: 3.1 MB for a single image in the slider on the edgi main page :(
https://envirodatagov.org/wp-content/uploads/2017/05/20030403-3525766316_8d71b04961_o.jpg

I did a pass to clean up images before, and thought I did all of the hero ones, but must have missed/not properly relinked

**Comment by patcon** [comment]
Maybe for lazies? https://rsz.io/#docs

**Comment by dcwalk** [comment]
I just processed 'em locally and re-uploaded. They currently aren't displayed as we have the 100days report on the modal. Closing for now
