### ISSUE TITLE
Typo: Interviewing Project Page - "December 2017" -> "December 2016"

### ISSUE THREAD

**Issue by blue-ice** [edgi-govdata-archiving/edgi-website#28]
On the page [https://envirodatagov.org/interviewing/](https://envirodatagov.org/interviewing/), please modify this sentence in the first paragraph to include the correct calendar year.

*Original*
> Trained interview teams in Washington DC, Boston, the San Francisco Bay Area, New Jersey, Colorado, and Vermont began confidentially interviewing long-term EPA and OSHA employees in December 2017, and since then have conducted 58 interviews.

*Modified*
> Trained interview teams in Washington DC, Boston, the San Francisco Bay Area, New Jersey, Colorado, and Vermont began confidentially interviewing long-term EPA and OSHA employees in December **2016**, and since then have conducted 58 interviews.

**Comment by dcwalk** [comment]
Oop, thanks for the catch @blue-ice!

I've corrected the year and changes are live https://envirodatagov.org/interviewing/
