### ISSUE TITLE
Add mission statement to homepage

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/edgi-website#30]
From 2017-08-07 website meeting:
> Homepage
> - Change button to go to recent highlights, reset the image
> - Then guide the user towards the mission. Link to the mission section of the homepage from the hero image. 
>- Put mission statement on About/Overview page

**Comment by lourdesvera** [comment]
@dcwalk am I correct that this is stalled until the 4S meeting?

**Comment by dcwalk** [comment]
The proper mission statement can't go up until after Boston, but the rest can be done!
Was totally slammed this week, just gonna get to now :)

**Comment by dcwalk** [comment]
Okay, I've done a preliminary update which should last us until end of August! https://envirodatagov.org/ Ticketed the next step in #36
