### ISSUE TITLE
Show cover thumbnails on Publication page

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/edgi-website#34]
Request from @suchthis in [Slack](https://edgi.slack.com/archives/C3EF5T7T6/p1501866621806693): 

> Had a quick latenight thought that it might be cool to list our reports kind of like UCS does, with a pic of the cover and a short blurb. They look so official…
> http://www.ucsusa.org/search/reports
> (Re. this page: https://envirodatagov.org/publications/)

I think this is a nice idea! The [example page](http://www.ucsusa.org/search/reports) from UCS looks 👍  this should be technically possible using the Custom Views plugin.

**Comment by Frijol** [comment]
Can we use blurbs from the annual reports for this? Seems like it would be useful for our communications push as well/we should in general have a thumbnail and blurb to accompany reports

**Comment by Frijol** [comment]
I still think this is a really good idea

**Comment by Frijol** [comment]
@lightandluck did this, it's great! https://envirodatagov.org/publications/
