### ISSUE TITLE
Clarify text around DataRescue sponsorship

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/edgi-website#35]
On this page: https://envirodatagov.org/datarescue/

> DataRescue events were organized by local coordinators and sponsored by EDGI and DataRefuge.

[On Slack](https://archivers.slack.com/archives/C3XS9LPJN/p1502309034970390?thread_ts=1502212772.115024&cid=C3XS9LPJN), one datarescue organizer reasonably sought clarity on whether other events had received sponsorship *funding*.

@jeffreyliu clarified that he understood funding to be the exception more than the rule.

Perhaps we could clarify this in the website text? (Personally, I'm not sure what the actual data is on this, so not sure what suggested alternative text to offer.)

**Comment by jeffreyliu** [comment]
Yeah, I can speak for some of the Boston events: the one at Harvard was sponsored mainly by Harvard departments and programs, the one at MIT received some funding from EDGI, but was primarily funded (~92%) through MIT-related sponsors. EDGI and Data Refuge provided help for the events through coordination, tools, guides, training, and publicity.

**Comment by dcwalk** [comment]
Yeah this flub is on me, it is just a language issue. I was trying to not use the word facilitated. Would "supported" be better?

My sense is that financial sponsorship was only ever a minimum, and most support was vol'n time from both orgs, coupled with sheparding the resources that were co-developed by attendees.

**Comment by jeffreyliu** [comment]
yeah, I think something along the lines of:
> "DataRescue events were organized by local communities with coordination and support from EDGI and DataRefuge."

might work better?

**Comment by dcwalk** [comment]
Okay I've updated! Thanks for the catch you two :) https://envirodatagov.org/datarescue/
