### ISSUE TITLE
Point "Our Work" nav link to front webpage, not just `#main` anchor

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/edgi-website#38]
## Observed behaviour

When on the front page, clicking the "Our Work" link in the navbar scrolls the screen down to the section of the page that details our projects.

When _not_ on the front page, this link simply goes to the `#main` id on that page, which is just the main content area.

## Expected beahviour

I would expect to be taken back to the front page and presented with the section that lists all our projects.

------

Assuming the expected behaviour above is the right thing to do, I think we can address this by simply using the full link in nav. When on the front page, it will just scroll, but when not, it will link there.

**Comment by patcon** [comment]
Went to investigate exactly how this would be done, but I don't think my "patcon" user has access to see menu config.

It seems that we don't have indication of "privileged access users" in our [Services & Deployment doc](https://paper.dropbox.com/doc/Services-Deployment-pTsHUVIb2JuFHo8KVfpq2). (We normally add a "trophy" emoji after the names of people with elevated access.) If someone with access to view users and permissions could advise me, I'd be happy to update that!

**Comment by dcwalk** [comment]
All the people listed in the services doc are at least Admin @patcon, which I thought was the convention we were using? We aren't listing all users in Slack, Docker etc... if they have "user" privileges, or haven't been... maybe there was a misunderstanding on my part about level of granularity.

would you like to also be added as one?

**Comment by dcwalk** [comment]
There isn't any easy way to get the link to go to the mainpage section that is intended, I've updated the link to `https://envirodatagov.org/#pg-1286-1` as that is the panel section, however when visiting from another page it isn't properly directing there. Using `#main` doesn't exhibit the same behaviour, so this is the best temp sol'n...?

Anyway, we've discussed having a separate "our work" section, maybe this should be revisited elsewhere?

**Comment by dcwalk** [comment]
@patcon, I am going to close this, as I think the intent has been solved, but due to limitations discussed above in a less ideal way.

Please re-open if you feel this wasn't addressed

**Comment by patcon** [comment]
Just sharing this link for later: https://stackoverflow.com/a/43168456/504018

The little loading animation is likely what's causing anchors to get ignored, but I'm not sure yet how to run the little piece of code (through the link) after the animation
