### ISSUE TITLE
Formatting errors on high-resolution screens

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/edgi-website#41]
See: https://100days.envirodatagov.org/epa-under-siege.html

On a high-resolution screen (like a 4K) or when zooming out to a comparable degree via browser controls, the bottom of the page starts displaying very oddly, with tons of whitespace and a jumpy, glitchy scrollbar. By the way the glitching happens, it might be related to the "Back to Appendix Themes" button that hovers when at the bottom of page.

cc: @dcwalk

**Comment by dcwalk** [comment]
Should this be in this repo or in https://github.com/edgi-govdata-archiving/100days

**Comment by dcwalk** [comment]
Closing as issue moved to https://github.com/edgi-govdata-archiving/100days/issues/44
