### ISSUE TITLE
Add EDJ 100days author bios

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/edgi-website#44]

**Comment by dcwalk** [comment]
I've reached out via Slack, will email tomorrow if people do not respond

**Comment by dcwalk** [comment]
Emailed and 2 more up!

**Comment by dcwalk** [comment]
@lourdesvera -- cc'd you on the last bio reminder email!

**Comment by lourdesvera** [comment]
Putting up Becky's bio now

**Comment by dcwalk** [comment]
Whoop whoop! 🎉 
Looks like it is up, I'm closing :)
