### ISSUE TITLE
Feature GSoC projects under "Our Work"?

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/edgi-website#45]
From Slack @suchthis:
> It might be nice to feature our GSoC projects a little more prominently, so we can start fanning the flames for next year! Our GSoC program doesn’t fit perfectly under any menu header, but maybe it could go under Our Work, at least for now, since it spans both archiving and WM? I’m thinking maybe it’s ok for that menu not to be a strict representation of working groups, since the site audience is the public, who prob don’t know or care what our WGs are

**Comment by dcwalk** [comment]
My reply from Slack:
I agree with both of these heartily! Would love to talk through both integrating the tech side more and also figuring out how to feature GSoC

I think that having a “structure” under about might cover our working group model, and then we could highlight our work a little differently?

**Comment by lourdesvera** [comment]
I'm not sure about this because it isn't a working group in itself and might take away from the website clearly representing the structure of EDGI. It's a little awkward on the events menu too, but I think it works?

**Comment by dcwalk** [comment]
Agreed! I think the question was raised by someone else. I'm going to close as wontdo for now :)
