### ISSUE TITLE
Add /blog/ to Blog posts url slug

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/edgi-website#47]
Currently all blog posts have a url path that is indistinguishable from a page:
envirodatagov.org`%postname%/`
e.g. : https://envirodatagov.org/website-monitoring/ appears the same as https://envirodatagov.org/towards-edj-statement/

I'm proposing we add `blog/` or `blog/<year>/<month>` to the url path:
envirodatagov.org`/blog/%year%/%monthnum%/%postname%/`
Making the above example: https://envirodatagov.org/blog/towards-edj-statement/ or https://envirodatagov.org/blog/2017/09/towards-edj-statement/

The reason I'm suggesting this is:
- this brings our blog in line with publications (e.g. https://envirodatagov.org/publication/the-epa-under-siege/)
- this distinguishes different types of content

If we want to go ahead with this the steps are:
- [ ] Update [Permalinks](https://envirodatagov.org/wp-admin/options-permalink.php)
- [ ] Set up redirects from existing paths (would suggest mapping this out with a spreadsheet
- [ ] Test!

**Comment by Frijol** [comment]
I think this is a good idea but don't have a good sense of what quantity of work it would be to implement / if it can be templated into workflow easily or would need to be done manually for new posts. Is it manual for publications?
