### ISSUE TITLE
Add Amazon as in-kind donor

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/edgi-website#48]
Amazon gave us $50K in AWS credits! Feels like they should be on our website with the other in-kind donors: https://envirodatagov.org/about/

cc: @shapironick @Mr0grog

**Comment by shapironick** [comment]
Thanks! Yes, as mentioned on slack. I asked them about what they want in terms of public acknowledgment and they are checking with their branding team and will get back to us. I think we should avoid posting publicly until we hear back from them. 

Sent on the move

**Comment by dcwalk** [comment]
If I understand this correctly we were told to defer for now. I'd favour closing this as won't do and then revisiting only if we are contacted/told otherwise.

Feel free to revisit if this is an issue

**Comment by Mr0grog** [comment]
Re-opening because they sent updated logo/branding info (they deferred because they were redesigning AWS’s brand materials):

- https://aws.amazon.com/trademark-guidelines/
- https://aws.amazon.com/co-marketing/

**Comment by shapironick** [comment]
Implemented. Weird that the orange of the aws arrow and the data kind logo are exactly the same and kinda blend into eachother.
