### ISSUE TITLE
Add PageFreezer as in-kind supporter

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/edgi-website#49]
I know we're moving off them, but it seems like we could give them a h/t here: https://envirodatagov.org/about/

Thoughts?

cc: @Mr0grog @danielballan

**Comment by Mr0grog** [comment]
I know we had some sort of agreement about attribution; @trinberg and @ambergman know details.

**Comment by lourdesvera** [comment]
Hi from 5.5 months in the future - I just asked @trinberg if we should add them

**Comment by lourdesvera** [comment]
Doh - I added them but then they disappeared again from the site. Adding again.
