### ISSUE TITLE
Address feedback on testing site

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/edgi-website#5]
A testing site was set up at [flolab.org/wp19/](http://flolab.org/wp19/), and the following feedback was suggested:
(Will but out separate issues as needed)

@dcwalk:
~> 1. My first thought — I’m nervous that the headlines seafoam isn’t sufficiently perceivable. When I use the html codesniffer tool I’m getting "Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.33:1. Recommendation: change text colour to #198573 .” > https://www.w3.org/TR/WCAG20/#perceivable~ (@dcwalk: reticketed)
~> 2. Could all the site buttons be styled the same? (e.g. flat with the colours?)~
~> 3. I think we were talking about footer nav too?~

M:
~> 4. the three linked pages above the description of the working groups- are those intended to stay articles? or could they link to particular projects (maybe rotating highlights?) in EDGI?~ (@dcwalk: was just for testing! Won't be articles)
~> 5. on the content pages, things are really squished in the side bars (for example the about page). is there a way to have recent posts, categories, and tags on the bottom?~
~> 6. an idea was floated that instead of "blogs" we would have reports or publications, and link everything.~ (@dcwalk: have publications & blog)
~> 7. the airtable for media coverage: do we still want to display that? it looks a bit strange, but maybe we can make it a drop down or something to only display if you click on it?~ (@dcwalk: updated with some better highlights, left below the fold tho)
~> 8. on the contact page, it's hard to know to scroll down to see actual contact information. can we either swap the form and the names, or put a note on the top of the page to indicate that there are people listed below?~ (@dcwalk: have condensed and rethought structure)

MH:
~> 9. This is perhaps a stylistic choice, but the size of the font used for Home/About/Blog etc. in the `upper right seems too small. Obviously it was a deliberately style choice to make it small, but it is _so_ small (at least for me under Safari) that it looks like CSS gone wrong. (edited)~ (@dcwalk: increased!)
~> 10. I don't know how others feel about tag clouds, but I find the completely useless. It's gotten to the point where I abhor seeing them on pages. I would skip the tag clouds and use the space for something better.~ (@dcwalk: removed!)

PB:
~> 11. look and feel is great .  I do notice that the main tab for press - "top stories" doesn't have the latest coverage , though some of that shows up in the "more" .~ (@dcwalk: updated~)  
~> 12. should there be links for other groups doing similar things to us, e.g. Rapid Response Network out of UCSF?~ (@dcwalk: reticketing #18)

MM:
~> 13. On my computer, the double side bar on about  is making things squished.~
~> 14. Instead of tags on side bar, upcoming events listing might be more useful to people interms of widget, if the event calendar has that capacity. (sidebar:  top going down: textbox with two sentence EDGI description, recent posts, event calendar. Get involved button.)~ (@dcwalk: tags removed, reticketing sidebar convo to #17)

L:
~> 15. on the content pages, things are really squished in the side bars (for example the about page). is there a way to have recent posts, categories, and tags on the bottom?~
~> 17. Should we add "contact" and "in the media" as dropdown items under “About”? I’d like to keep going down the minimalist route.~ (@dcwalk: removed Contact to the footer, we are at 6 global menu items! leaving at this for now)

SW:
~> 18. We should add a tabs for "funding", and "EDGI members" to "about".~ (@dcwalk: content added to About, not always as tabs)
~> 19. The "get involved" section on the home page is entirely directed at Archiving at present and needs to be redesigned.~ (@dcwalk: preliminarily reshaped, but future home page improvements to be made) 
~> 20. The lead content needs to be slightly rewritten to focus on the actual current projects and include links to them~ (@dcwalk: updated, in particular moved stuff to about)
~> 21. I really think the "blog" tab needs to be replaced with "Publications" tab that has two sub headers "blog" and "articles/reports". ~ (@dcwalk: both are currently top level nav)
~> 22. the subheading "reports" should be pulled out of "projects", and put with publications (see point 4).~ (@dcwalk: addressed!)

**Comment by trinberg** [comment]
Sorry for the delay, since this is just a first pass - I propose the following tentative restructuring of the Website Monitoring and CPF parts of the website @dcwalk @devinbalkind 

- Website Monitoring
  - Reports
  - Patterns and Themes Analysis
(If Agency Info just means primers, I wouldn't put that in here - it should go with archiving and it seems like it's already there )
- Capacity & Governance  (instead of Building Capacity)
   - Legislative Tracking (instead of Bill Tracking)
   - FOIA 
   - Budget Tracking

(I think we'll likely add more to the Capacity & Governance domain, but this will be a good start)

**Comment by dcwalk** [comment]
@trinberg -- I want to sit on the Website Monitoring IA -- it seems odd to bury the reports there when we are hoping to surface/collect all the rest under publications.

RE: Capacity & Governance can you point me in any description etc... so we can begin to tackle content (see #10). I am still having a hard time understanding the breadth of what CPF does and don't understand how "governance" fits into a project ATM.

**Comment by trinberg** [comment]
@dcwalk - I'm sitll not sure how the website monitoring page will be structured, but I do think we should have the reports and articles based on our reports listed under that domain and in one place. Sort of like it's done now: https://envirodatagov.org/website-monitoring/  Perhaps the reports can ALSO be listed under publications?

Regarding Capacity & Governance (or whatever we'll end up calling it) - This'll definitely be many projects, but we're still figuring out how to organize and group them. Maybe we can have a quick conversation some time early this week about this? And I'm not sure a nice comprehensive doc explaining this working group exists, but I'll dig around for it.

**Comment by dcwalk** [comment]
Closing this as resolved because all of the feedback has been reconciled :), have ticketed out the remaining issues for further discussion.
