### ISSUE TITLE
Calendar on envirodatagov.org/events/ opens to November 2017, outdated text

### ISSUE THREAD

**Issue by ebarry** [edgi-govdata-archiving/edgi-website#52]
Hi! Just observing that the calendar on https://envirodatagov.org/events/ opens to a view of November 2017, which is unexpected considering that it is March 2018. 

Perhaps this whole page needs a refresh: 

- [ ] load the Google Calendars for EDGI and Data Together instead of the AirTable view (this should fix the date issue)
- [ ] update the header text now that DataRescue events aren't happening in the same way

**Comment by lourdesvera** [comment]
@ebarry Yes! I'm not sure how public we want the EDGI meeting calendar to be to non-members, so I posted a message in the #communications EDGI slack channel. Can you post a link to the Data Together calendar so I can get that up? Thanks.

**Comment by dcwalk** [comment]
Agree this needs to be updated regardless! 

@lourdesvera The Data Together events are also in the EDGI calendar

Just moving my comments from Slack here. The only things I would surface are:
- not losing the history of events from the airtable, as that has the canonical list of Data Rescues
- previously people were concerned about internal deadlines and call links being publicly published, I think that should be discussed so people are all on the same page about what is being shared publicly

**Comment by dcwalk** [comment]
This actually has been resolved as we now show internal meetings with a message about joining: https://envirodatagov.org/events/ ! Closing
