### ISSUE TITLE
Map that updates from member list data

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/edgi-website#53]
@lourdesvera created and looks after updating a [totally amazing map](https://envirodatagov.org/about/members/) that helps visitors to our website understand our geographic breadth as an organization.

**D3.js** is a visualization library that helps make dynamic visualizations in webpages.

There are two D3 visualization demos that we could steal from and remix into one:

[**Basic US State Map.**](http://bl.ocks.org/michellechandra/0b2ce4923dc9b5809922) It builds a pretty map from a simple geoJSON file. We could pretty easily find a file for Canada too.

[**Automatic floating labels using d3 force-layout.**](http://bl.ocks.org/ZJONSSON/1691430) It generates random x,y "points" and then draws labels to them, with arbitrary information on labels.

Helpful question related to connecting them: [How to convert latitude and longitude into (x,y) coordinates using d3.js](https://stackoverflow.com/questions/43160459/how-to-convert-latitude-and-longitude-into-x-y-coordinates-using-d3-js)

I feel that this might be a good entry task for a new member who is interested in growing skills with D3. But maybe there are better things, so just stubbing out idea for now :)

The above could be generate from Google Sheets data or Airtable -- whichever works

**Comment by patcon** [comment]
Our expertise survey is where the location information currently lives in GDrive:

- "EDGI - Expertise Survey (Responses)" (not linked because not a restricted doc)

Google Maps reverse geocoding API can be used to map locations to map points:
https://maps.googleapis.com/maps/api/geocode/json?&address=New%20Haven,%20CT,%20USA

**Comment by dcwalk** [comment]
we could repurpose our DataRescue map code as a first point? or connect the
data source to the way the current map is generated (is it tableau?)

**Comment by patcon** [comment]
Re: https://github.com/edgi-govdata-archiving/datavis-projects
