### ISSUE TITLE
Archiving Page audit: questions & needed updates

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/edgi-website#56]
I realized today that despite our purpose of archiving data to preserve public access... I still don't know what exactly we have archived, or where to find it. That's a big problem! I should know that! We all should know that & publicize it!

I went through https://envirodatagov.org/archiving/ (where I would expect people to look for this information) & took these user test notes.

### How to interact with these notes
Formatting key: *Italics* means I can just put in a PR to fix it; **bold** means I need someone to help me find the answer. All other text is just stuff I noticed– up for discussion re whether any change is needed. (~strikethrough~ means I already changed it on Wordpress)

Please read through & respond with any knowledge/opinions, ideally quoting which note you are responding to in the reply.

## Intro
* *Remove Summer of Code button*
* Main focus is on archive-a-thons and the data preserved from there
* Data Together presented as "the next phase of archiving", points to blog post from July 2017 (this post is not very detailed. Point instead to the Data Together Github? Somewhere else?)

## Vulnerable Data section
* **Vulnerable Data section is excellent & actionable assuming the links are still the right places to point people. Are they?**
* "Check whether it has already been preserved"– how does a visitor to this site know where to look? Should they just try all three places?
* Internet Archive
  * If you're looking for something specific, how do you find it? Are there docs for this?
  * ~The End of Term Archive site (https://web-beta.archive.org/details/collection-eot2016-waybacksummary) links to a beta test site that is now closed. **Is there a live site we can link to?**~
* Archivers.Space
  * Can you get data from here, or is it just a map of sites?
  * **In general, how should this be used?** Are there docs? It's not obvious that you're supposed to click on the dots by http/https/ftp to see more depth, easy to just get to the first page and be stymied
  * Who owns this site? There's no logo or "About" link. Based on the design of https://alpha.archivers.space/ I assume it's a Data Together project– **are we actively working on this?** Is it [this archived EDGI repo](https://github.com/edgi-govdata-archiving/archivers.space)?
* CKAN (DataRefuge) seems relatively easy to find data in, but partly because there's not much there (just 10 datasets from the whole CDC? Doesn't seem right..) and what there is often dates back to 2017
* **Nomination tools: are these currently functional/do their outputs go somewhere?**
* Bookmarklet: I followed the instructions to add to Chrome and it didn't do anything :(. Chrome extension seems to work though!
* ~*"We've making significant progress in 2018" & callback to annual report– I suggest we remove this line*~

## This is a Movement section
* ~*"Take a look at our Project board"– would like to remove this in favor of the readme of the overview page (one canonical place to say how to get involved)*~

**Comment by Mr0grog** [comment]
I believe the EOT Archive.org URL you want is 
https://archive.org/details/EndOfTerm2016WebCrawls. There is also 
http://eotarchive.cdlib.org/

**Comment by Frijol** [comment]
we're eventually working on this [website copy](https://docs.google.com/document/d/16Si2RgXuF_75fg2tRFx_EgnMhzKkagm385deKQMBF4A/edit) cc @EDGI-Comms
