### ISSUE TITLE
Ensure colour scheme meets accessibility guidelines

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/edgi-website#6]
From #5 .1:
 > When I use the html codesniffer tool I’m getting "Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.33:1. Recommendation: change text colour to #198573 .” > https://www.w3.org/TR/WCAG20/#perceivable

Resources:
- https://www.w3.org/TR/WCAG20/
- https://squizlabs.github.io/HTML_CodeSniffer/
- Chrome extension "Accessibility Developer Tools"

**Comment by lightandluck** [comment]
@dcwalk - I looked at the parent issue #5 and the color change was referring to 
> headline seafoams

What are those?
