### ISSUE TITLE
"About" page urgently needs a refresh

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/edgi-website#62]
Here's the top of the current [About page](https://envirodatagov.org/about/):

![Screen Shot 2019-05-24 at 12 14 57 PM](https://user-images.githubusercontent.com/454690/58351450-ae018f80-7e1d-11e9-8dd6-77b50c2e7415.png)

The main text of the About page reads like it was probably current in spring of 2018 but now shows clear signs of datedness (link to old annual report, citing number of reports published, etc.).

**What do we want people to know about us when they come to this page? What is important to link to, and what story do we want to tell?**

* Do we want to highlight the links we currently highlight here? If so, do they belong at the top or the bottom of the page?
* What are the main points we want people to take away from this page?

[Here](https://docs.google.com/document/d/1q2Xo1v5jDTGwxtu-v5rLkgRpUQzumXqG3EqZIO4JRFk/edit) is a google doc for comments and suggestions on the existing text of the page.

**Comment by Frijol** [comment]
@EDGI-Comms the page looks different now than in my screenshot, can we close this?

**Comment by EDGI-Comms** [comment]
Yes, these were updated!
