### ISSUE TITLE
Coverage image on Press page is current to 2/2018

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/edgi-website#67]
On the [Press Page](https://envirodatagov.org/press/):
![Screen Shot 2019-05-24 at 1 20 42 PM](https://user-images.githubusercontent.com/454690/58354627-e8235f00-7e26-11e9-8708-58e33e1bb02e.png)
![Screen Shot 2019-05-24 at 1 20 48 PM](https://user-images.githubusercontent.com/454690/58354636-ebb6e600-7e26-11e9-98b7-d60fe46e8fc4.png)

We have an update to this image we can replace with from the 2019 Annual Report, right?

**Comment by Frijol** [comment]
@EDGI-Comms is this still true?

**Comment by EDGI-Comms** [comment]
The graphics are old. Personally I think we should just take them down rather than updating them. I don't think they're interesting to the general public, or that clear. What are your thoughts?

**Comment by Frijol** [comment]
That seems reasonable to me, they're in the annual reports if we need to find them

**Comment by EDGI-Comms** [comment]
Okay cool -- just removed them from the Press page.
