### ISSUE TITLE
Highlight current content on the frontpage

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/edgi-website#7]
From #5 .4, 19, 20:

TODOs
- [x] update focus areas to projects
- [x] revamp and update text to not be archiving focused and mention all current projects

**Comment by lourdesvera** [comment]
draft page: https://envirodatagov.org/1286-2/

**Comment by lourdesvera** [comment]
To Do
- [ ] Hero image above icons?

**Comment by dcwalk** [comment]
It looks good! I'm wondering if maybe we switch to a full screen layout, feature the donate button as a call to action, and maybe take advantage of the custom widget layouts?

In particular....
![screen shot 2017-05-11 at 12 09 22 pm](https://cloud.githubusercontent.com/assets/4692834/25959752/bb9bf4f2-3642-11e7-90a5-ae4aa7f6526b.png)

or this...
![screen shot 2017-05-11 at 12 09 17 pm](https://cloud.githubusercontent.com/assets/4692834/25959770/cad97f8e-3642-11e7-800a-7c77f55e81f9.png)

**Comment by dcwalk** [comment]
This was done (yay 🎉 )
